# variable definitions
# DO NOT CHANGE MANUALLY - GENERATED BY STATEFILES GENERATOR MODULE

variable "platform" {
  type = object({
    tenant_id       = string
    subscription_id = string
    location        = string
    state_rg        = string
    state_storage   = string
    state_container = string
    keyvault_name   = string
  })
}