# Generated backend configuration for Terraform remote state
# DO NOT CHANGE MANUALLY - GENERATED BY STATEFILES GENERATOR MODULE

resource_group_name  = "an_platform_state_rg"
storage_account_name = "anplatformstate"
container_name       = "tfstate"
