# _basics.tf
# Generated automatic variables configuration
# DO NOT CHANGE MANUALLY - GENERATED BY INIT_PROJECT
variable "basics" {
  description = "Basic configuration for the environment"
  type = object({
    base_name   = string
    environment = string
  })
  default = {
    base_name  = "text-e"
    environment = "dev"
  }
}
