# variables
# DO NOT CHANGE MANUALLY - GENERATED BY STATEFILES GENERATOR MODULE

platform = {
  tenant_id       = "9c0f6304-c41a-4891-8379-ed3cbfc54535"
  subscription_id = "93a208c4-9c58-4f97-b35f-9beb52df1041"
  location        = "switzerlandnorth"
  state_rg        = "an_platform_state_rg"
  state_storage   = "anplatformstate"
  state_container = "tfstate"
  keyvault_name   = "affolternet-vault"
}
