#!/bin/bash

# author: martin@affolter.net

# DO NOT CHANGE MANUALLY - GENERATED BY STATEFILES GENERATOR MODULE

yellow() { printf "\e[33m$*\e[0m\n"; }
green() { printf  "\e[32m$*\e[0m\n"; }
red() { printf  "\e[31m$*\e[0m\n"; }
blue() { printf "\e[34m$*\e[0m\n"; }

env=${1:-"dev"}
client_id="$(az keyvault secret show --name an-platform-state-${env}-sp-client-id --vault-name affolternet-vault --query value -o tsv)"

# Check if already logged in with the desired client_id
current_client_id="$(az account show --query user.name -o tsv 2>/dev/null || echo "")"

if [ "$current_client_id" = "$client_id" ]; then
    green "Already logged in with client_id: $client_id for environment: $env"
    exit 0
fi

client_secret="$(az keyvault secret show --name an-platform-state-${env}-sp-client-secret --vault-name affolternet-vault --query value -o tsv)"
az login --service-principal -u $client_id -p $client_secret --tenant 9c0f6304-c41a-4891-8379-ed3cbfc54535

yellow "logged in to \"$env\""