#!/bin/bash

# author: martin@affolter.net

# DO NOT CHANGE MANUALLY - GENERATED BY STATEFILES GENERATOR MODULE

yellow() { printf "\e[33m$*\e[0m\n"; }
green() { printf  "\e[32m$*\e[0m\n"; }
red() { printf  "\e[31m$*\e[0m\n"; }
blue() { printf "\e[34m$*\e[0m\n"; }

# Check if already logged in with the desired client_id
client_id="5700c6f1-4c18-44db-962d-a7d437d1b424"
current_client_id="$(az account show --query user.name -o tsv 2>/dev/null || echo "")"

if [ "$current_client_id" != "$client_id" ]; then
    red "Wrong client_id: $current_client_id. Please run 'az login' first."
    exit 0
fi
# set the correct subscription
az account set --subscription "93a208c4-9c58-4f97-b35f-9beb52df1041"

terraform init -backend-config=_backend.hcl -reconfigure

yellow "Initialized Terraform for module: text-e/prod/kc"